"""initial tables

Revision ID: 06bd93681223
Revises: 
Create Date: 2026-09-21 10:50:58.007763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bd93681223'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='research_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_created_at'), 'research_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_topic'), 'research_runs', ['topic'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_research_run_id'), 'agent_runs', ['research_run_id'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('target_users', sa.Text(), nullable=True),
    sa.Column('mvp', sa.Text(), nullable=True),
    sa.Column('monetization', sa.Text(), nullable=True),
    sa.Column('competition', sa.Text(), nullable=True),
    sa.Column('differentiation', sa.Text(), nullable=True),
    sa.Column('technical_complexity', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('validation_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'VALIDATED', 'REJECTED', 'BUILT', name='idea_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_created_at'), 'ideas', ['created_at'], unique=False)
    op.create_index(op.f('ix_ideas_research_run_id'), 'ideas', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_ideas_status'), 'ideas', ['status'], unique=False)
    op.create_index(op.f('ix_ideas_title'), 'ideas', ['title'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('WEB', 'ACADEMIC', 'NEWS', 'GITHUB', 'OTHER', name='source_type'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_ideas_title'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_status'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_research_run_id'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_created_at'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_agent_runs_research_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_research_runs_topic'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_created_at'), table_name='research_runs')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
